experiment_name: 'example_run_2'
model: 'dg1'  # Available choices: dg1
mode: 'ti'  # pretrain, train, inference, pt, pti, ti
cas: 'cas9_seq'  # cas9_seq

guide_length: 28  # Default 28

# Only if pretraining. fasta file containing the entire genome.
# Place in the input directory.
pretrain_genome_input_name: 'CBS6556GenomewSimplifiedHeaders.fa'

train_guides_csv_file_name: 'example_train.csv'  # Must be a .csv
train_guide_seq_col_name: 'guide_with_context'  # The name of the column in the training set that contains the guides with flanking context base pairs
train_guide_score_col_name: '30dC_2%_glucose_CS_day2_normalized_by_NT_avg'  # The name of the column in the training set that contains the true experimental scores

inference_guides_csv_file_name: 'example_test.csv'
inference_guide_seq_col_name: 'guide_with_context'

# Output a diagram that shows the ML architecture?
# Requires Pydot, and Pydotplus -- Not required to run an experiment.
# Feel free to disable (set to False) if you don't have those packages.
plot_model: False

# ----------------------
metrics: True  # Switch to True for large enough data -- Won't work with examples
plot_auc_curve: True  # Switch to True for large enough data -- Won't work with examples
# ----------------------

# DG1 HYPERPARAMETERS
dg_one_pretrain_train_test_ratio: 0.7  # Default: 0.7 Means 70% of data used for training and 30% for validation.
dg_one_train_test_ratio: 0.7  # Default: 0.7
dg_one_adam_lr: 0.003  # Default 0.001
dg_one_roc_curve_threshold: 3
dg_one_batch_size: 64
dg_one_epochs: 10
